# Generated by Django 3.2.12 on 2022-04-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatID', models.CharField(max_length=10)),
                ('candidName', models.CharField(max_length=60)),
                ('percentWin', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=3)),
            ],
        ),
    ]
