# Generated by Django 3.2.12 on 2022-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electionapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectionResults',
            new_name='ElectionResult',
        ),
    ]
